### ISSUE TITLE
my soulanchor does not display chapters

### ISSUE THREAD

**Issue by mindiae** [Anchorm/SoulAnchor#1]
i have 1.09-1 version from aur and my soulanchor does not display chapters except in gospels and acts and general epistles. in other books it only displays first chapter and there is no way i can navigate to other chapters

**Comment by Anchorm** [comment]
Hi, have you used an older version in the past? If so, can you uninstall and make sure all old files are removed before using 1.09.

Also, are you using the default database with NET bible?

**Comment by mindiae** [comment]
i have been using custom imported translations of bible and i have removed all and just loaded one and it fixed the problem thanks for the attension

**Comment by Anchorm** [comment]
Nice. SoulAnchor checks the chapter (c) column in the database, for the active translation, to determine the amount of chapters. So if you get this problem again make sure that column has the correct data.

**Comment by mindiae** [comment]
everything fixed
